# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3bc86a6451f47b2c0df726cdfef7c0378ebfa6f6b780af932e03cb8abe3feb07a0c98f4b40545b1e16f45c075a153323dcd965020147b2d2063b68552731a617

test:
  secret_key_base: 6dacf6b71f7072e2b31bc45b8598162a4f4590a39172656388c1c7ffa23919fd61227226318dde870273b561052ad5f3428e7bf4cedd7dfaa36fbbb96bf4d55f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
